//水印控制
const WATER_MASK = "WATER_MASK"
//面包屑控制
const BREAD_CRUMB = 'BREAD_CRUMB'
//标签栏控制
const TAB = 'TAB'
//主题色
const PRIMARY_COLOR = 'PRIMARY_COLOR'
//导航模式
const NAVIGATION_MODE = 'NAVIGATION_MODE'

export {
  WATER_MASK,
  BREAD_CRUMB,
  TAB,
  PRIMARY_COLOR,
  NAVIGATION_MODE
}
